### ISSUE TITLE
请问怎么监听或者判断连接失败呢？

### ISSUE THREAD

**Issue by weiqinke** [liuhuisheng/ali-mysql-client#1]
你好，我在项目中使用了您的插件，我现在找不到连接失败的监听事件，或者说如何判断连接失败，进行重新连接呢？

**Comment by liuhuisheng** [comment]
项目底层是使用alirds进行连接的，可看下alirds这里的连接错误处理：https://github.com/ali-sdk/ali-rds/blob/master/lib/client.js#L46，如果你想自己使用mysqljs控制连接也可以传入一个mysql对象，new DbClient({ msyql })也支持

**Comment by liuhuisheng** [comment]
项目底层是使用alirds进行连接的，可看下alirds这里的连接错误处理：https://github.com/ali-sdk/ali-rds/blob/master/lib/client.js#L46，
如果你想自己使用mysqljs控制连接也可以传入一个mysql对象，new DbClient({ msyql })也支持
