### ISSUE TITLE
mysql 8.0.17 使用root账户联系时报错

### ISSUE THREAD

**Issue by vhvy** [liuhuisheng/ali-mysql-client#10]
服务器:                   centos 8
Mysql:                    8.0.17
ali-mysql-client:     1.0.4
开发机:                   win 10
nodejs:                   14.4.0

使用root账户远程连接到数据库时，会报出下面这样的错误
`
Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'192.168.x.x' (using password: YES)
      at Handshake.Sequence._packetToError (C:\Users\xxxxxxxxx\xxxxxx\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
`
按照 [stackoverflow](https://stackoverflow.com/questions/40477625/nodejs-mysql-er-eccess-denied-error-access-denied-for-user-rootlocalhost)的这个解释新建别的账户后可以正常连接。

另外您的这个库做的非常好用!

**Comment by liuhuisheng** [comment]
这个是mysql默认禁止了root用户的远程登陆的权限导致的问题，你开启下权限就好了网上应该有很多方案。
