### ISSUE TITLE
关于批量插入

### ISSUE THREAD

**Issue by cm971991** [liuhuisheng/ali-mysql-client#11]
INSERT INTO salary (
	employee_id,
	NAME
) SELECT
	id,
	NAME
FROM
	employee
请问下这样的批量插入语句该如何调用这个库的函数书写

**Comment by liuhuisheng** [comment]
文档中有写，支持传入数组
![image](https://user-images.githubusercontent.com/2784695/89730252-c506be80-da6f-11ea-80db-855ec40f29ec.png)

**Comment by cm971991** [comment]
谢谢
