### ISSUE TITLE
服务长时间运行后访问数据库会出现Too many connections

### ISSUE THREAD

**Issue by meguoe** [liuhuisheng/ali-mysql-client#14]
你好大神，最近遇到一个问题，服务长时间运行后访问数据库会出现Too many connections，通过查询，MySQL 中存在大量Sleep连接，排查了半天，没找到问题所在，不知大神能否帮忙分析下原因。

**Comment by liuhuisheng** [comment]
你可以看下你的代码是怎么创建实例的，我的示例中都是在app启动时创建一个实例然后复用，你是不是在每个请求进来都创建了实例，我的底层连接是alirds理论上来说这个包并不去解决连接问题只是解决查询构建的问题，当然连接也是没有问题的，我使用几年来并未碰到过你说的这种情况

**Comment by meguoe** [comment]
我参考您的示例创建配置，唯一的不同是我没有安装egg-mysql，而是new DbClient({conf}) 直接创建mysql连接的。不知道这样是否会导致出现我描述的问题。

**Comment by meguoe** [comment]
我现在已经安装了egg-mysql, 同时按照您相同的配置进行使用，观察一段时间看看是否会出现吧，谢谢大佬回复！
