### ISSUE TITLE
怎么配置表前缀

### ISSUE THREAD

**Issue by const-undefined-man** [liuhuisheng/ali-mysql-client#15]
我这里有好些表，但是都有前缀，比如xxx_user, xxx_role, xxx_menu
都有统一的前缀；xxx_user

我看了老半天也没有看到配置前缀的字段，麻烦帮忙看一下；

谢谢

------------

4月15日更新：

好些没有与表相关的功能，比如 创建表、更新表、添加表字段、更新表字段 等

**Comment by liuhuisheng** [comment]
没有特别处理前缀，可以直接写表名时加上，这个库没有提供ddl操作，如果想操作可以使用db.sql('ddl sql').execute()
