### ISSUE TITLE
是否可以支持Connection pool

### ISSUE THREAD

**Issue by kiyology** [liuhuisheng/ali-mysql-client#16]
哈喽，大神写的这个很赞，我看到之前有个closed issue里面说目前这个只是用了一个mysql connection来做的查询，想问一下能否支持connection pool呢？请求量大了之后如果只有一个connection的话是会排队吗？

**Comment by liuhuisheng** [comment]
这个不是sql builder这层的逻辑，在底层依赖的ali-rds，这层是已经做了连接池的，默认connectionLimit = 10，queueLimit=0，也支持传入配置
