### ISSUE TITLE
我咨询下，ali-mysql-client如何在查询后断开连接？谢谢

### ISSUE THREAD

**Issue by jeffreyshou7** [liuhuisheng/ali-mysql-client#20]
下列代码在查询完毕后程序不结束，查了相关资料，需要mysql的连接进行end(),请问贵ali-mysql-client如何操作，谢谢！

const db = new DbClient({
  host     : '127.0.0.1',
  user     : 'root',
  password : 'root',
  database : 'db_user'
});

const result = await db
  .select("*")
  .from("t_user")
  .queryRow();

console.log(result);

**Comment by liuhuisheng** [comment]
可以通过db.provider.command.mysql拿到ali-rds对象，调用release()试试

**Comment by jeffreyshou7** [comment]
感谢，兄弟！



***@***.***
 
发件人： 萧秦
发送时间： 2022-11-17 10:31
收件人： liuhuisheng/ali-mysql-client
抄送： Jeffrey Shou; Author
主题： Re: [liuhuisheng/ali-mysql-client] 我咨询下，ali-mysql-client如何在查询后断开连接？谢谢 (Issue #20)
Closed #20 as completed.
