### ISSUE TITLE
不能设置字符集吗

### ISSUE THREAD

**Issue by lmxdawn** [liuhuisheng/ali-mysql-client#21]

**Comment by liuhuisheng** [comment]
可以参考ali-rds配置中的charset
`const config = {
  host: 'your-rds-address.mysql.rds.aliyuncs.com',
  port: 3306,
  user: 'your-username',
  password: 'your-password',
  database: 'your-database-name',

  // optional params
  // The charset for the connection.
  // This is called "collation" in the SQL-level of MySQL (like utf8_general_ci).
  // If a SQL-level charset is specified (like utf8mb4)
  // then the default collation for that charset is used. (Default: 'UTF8_GENERAL_CI')
  charset: 'utf8_general_ci',
}`
