### ISSUE TITLE
时区

### ISSUE THREAD

**Issue by southfly** [liuhuisheng/ali-mysql-client#22]
你好，返回的日期数据，client可以设置时区吗，或者设置日期字段的返回格式，

**Comment by liuhuisheng** [comment]
你可以尝试在连接配置中增加timezone参数，const db = new DbClient({..., timezone: 'local'})，底层使用的是mysql.createPool(config)创建连接池，参考https://github.com/mysqljs/mysql

**Comment by southfly** [comment]
timezone: 'Asia/Shanghai'
我刚试了添加这个，返回时间格式，2022-11-24 23:40:45。谢谢。
