### ISSUE TITLE
没有断开 mysql连接 的方法吗？

### ISSUE THREAD

**Issue by gakkiox** [liuhuisheng/ali-mysql-client#23]
大佬，没有断开 此次mysql连接 的方法吗？

**Comment by liuhuisheng** [comment]
底层采用的是连接池的方案，无需对连接进行操作，https://github.com/mysqljs/mysql#pooling-connections， 每次查询等价于：pool.getConnection() -> connection.query() -> connection.release()，如果你要销毁连接池的话可以调用pool.end()但是没必要，连接池pool对象可以在db.provider.command.mysql对象中取到
