### ISSUE TITLE
bigint 数值获取会自动四舍五入？

### ISSUE THREAD

**Issue by meguoe** [liuhuisheng/ali-mysql-client#3]
我数据一个ID字段是bigint类型，一条数值为291008378255339540，但通过ali-mysql-client获取到的是291008378255339500（被自动四舍五入了），这个是否有参数可以控制不自动四舍五入？

**Comment by liuhuisheng** [comment]
底层也是直接调用mysqljs进行处理数据的，并没有做特殊处理
