### ISSUE TITLE
egg config 打印SQL日志不生效

### ISSUE THREAD

**Issue by meguoe** [liuhuisheng/ali-mysql-client#5]
按照示例配置设置了onBeforeExecute，onAfterExecute，onExecuteError，启动后能正常访问数据库，但无法打印日志，官方示例下载后启动也无法打印，麻烦看一下什么问题

**Comment by meguoe** [comment]
已解决new DbClient() 传入egg-mysql的问题！

**Comment by liuhuisheng** [comment]
应该是配置我的示例文件写的有点问题，已经修复了
