### ISSUE TITLE
ER_CON_COUNT_ERROR: Too many connections

### ISSUE THREAD

**Issue by inteye** [liuhuisheng/ali-mysql-client#6]
mysql连接过多，找不到别的办法了，请帮忙解答。

**Comment by inteye** [comment]
会有不自动释放连接的可能吗？show processlist里满是sleep，一会功夫连接就超限了

**Comment by meguoe** [comment]
> mysql连接过多，找不到别的办法了，请帮忙解答。

你这个问题解决了吗？我也遇到这个问题了。。。。
