### ISSUE TITLE
事件监听的配置错误了

### ISSUE THREAD

**Issue by hhnewbee** [liuhuisheng/ali-mysql-client#7]
https://github.com/liuhuisheng/ali-mysql-client/blob/cd52598ec71e06e1b779c20dc99f29e4fbc58b48/lib/configuration/index.js#L59

https://github.com/liuhuisheng/ali-mysql-client/blob/cd52598ec71e06e1b779c20dc99f29e4fbc58b48/examples/demo-egg/app.js#L15

这里的 `config.config` 和示例中的配置不符合，如果这样写正确的话，那么示例中的应为 
`{ config: { config: mysqlClient.config } }`

**Comment by liuhuisheng** [comment]
> https://github.com/liuhuisheng/ali-mysql-client/blob/cd52598ec71e06e1b779c20dc99f29e4fbc58b48/lib/configuration/index.js#L59
> 
> https://github.com/liuhuisheng/ali-mysql-client/blob/cd52598ec71e06e1b779c20dc99f29e4fbc58b48/examples/demo-egg/app.js#L15
> 
> 这里的 `config.config` 和示例中的配置不符合，如果这样写正确的话，那么示例中的应为
> `{ config: { config: mysqlClient.config } }`

看了一下的确是有问题，我已经修改示例文件了，感谢指正！
