### ISSUE TITLE
返回值是一个SelectBuilder的类，不是具体的值

### ISSUE THREAD

**Issue by BinghuiXie** [liuhuisheng/ali-mysql-client#9]
大佬你好，我在使用这个库的时候有一个疑问想问下，下面是我的代码：
`
// client.js
const DBClient = require('ali-mysql-client');
const mysqlConfig = require('../common/dbConfig');
const TABLES = {
    USER_TABLE: 'nj_user'
}

class DataBaseClient {

    constructor() {
        this.client = new DBClient(mysqlConfig);
    }
    /* 获取全部成员信息 */
    async getUserInfoList() {
        const result = await this.client
            .select('*')
            .from(TABLES.USER_TABLE);
        return result;
    }
}

module.exports = DataBaseClient;

// score.js
const Client = require('../utlis/client');
const client = new Client();
router.get('/', async function(req, res, next) {
    const result = await client.getUserInfoList();
    console.log('result: ', result);
});
`

result打印出来以后是这样的：
`
SelectBuilder {
  provider: MysqlProvider {
    config: Configuration {
      operatorMap: [Object],
      ignoreMap: [Object],
      eventSubs: []
    },
    command: DbCommand {
      mysql: [RDSClient],
      literals: [Object],
      config: [Configuration],
      trans: null
    }
  },
  data: {
    select: '*',
    from: 'nj_user',
    where: [],
    orderby: '',
    groupby: '',
    having: '',
    rows: 0,
    page: 0,
    fromArg: []
  }
}
`
不知道是为什么，望大佬帮忙解惑！感谢🙏

**Comment by BinghuiXie** [comment]
看了下源码返回的就是一个SelectBuilder的实例？

**Comment by liuhuisheng** [comment]
你这个只是构建查询返回了一个selectBuilder对象，还没执行command呢，你要client.select("*").from("xxx").where("...").queryList()才是查询数据库返回一个promise，需要最后加上queryValue，queryRow，queryList，queryListWithPaging查询的动作
